### ISSUE TITLE
Wig output option returns raw values, not log2 or bounded

### ISSUE THREAD

**Issue by ShanSabri** [WeiqiangZhou/BIRD#4]
The output_file.txt has a predicted upper bound set at 14, but the predicted values from the wig output using the same command ranges from zero to several thousand. The reason for this because the wig file is raw predicted values (unlogged and unbounded). 

For example, my predicted value for position chr19:4052801 in the output_file.wig is 628.885398; however the same location has a value of 9.298946 or log2(628.885398+1).

**Comment by WeiqiangZhou** [comment]
The wig format output the predicted values without log transformation (a usual way to record data in wiggle format since most track viewers, e.g., UCSC browser, provide the option to log-transform the signals). It is basically equal to 2^predicted_value - 1. It should be bounded by 2^14 or 2^up_bound if you provide the up_bound.

**Comment by ShanSabri** [comment]
Fair enough. 

IGV does not allow for log2 transform + pseudo count so might be useful to output log2 values that are comparable to the .txt, perhaps even indicated as a flag. Seems much easier to drag a track directly into IGV than reading in the .txt, transform log2+1 values, bound values, output to have the track match the .txt.

**Comment by WeiqiangZhou** [comment]
Good suggestions. I will add an option in the next version. A temporary solution is to replace lines 614-622 and lines 631-639 in "predict_function.cpp" with the following code: 
`					value = data_out[i][count];
					if (value < 0)
					{
						value = 0;
					}
					else if (value > up_bound)
					{
						value = up_bound;
					}
`

**Comment by WeiqiangZhou** [comment]
A new option (-wt) has been added to BIRD to output log-transformed values in wig format. Check it out.
