### ISSUE TITLE
RNAseq expression data input 

### ISSUE THREAD

**Issue by liangdp1984** [WeiqiangZhou/BIRD#6]
FPKM (hg19-based) is the only choice of input expression data for predicting DHS.  Can we use alternative quantification data such as RSEM, TPM etc?

**Comment by WeiqiangZhou** [comment]
The current pre-built hg19 model is based on FPKM. It is possible to use other quantification data such as TPM but that requires rebuilding the model based on TPM. This is a good point. I am going to release a new pre-build model based on TPM soon. I am not sure what you mean by RSEM since RSEM also reports FPKM and TPM. Do you mean the expected-count reported by RSEM?

**Comment by liangdp1984** [comment]
Thanks for your quick response!  TCGA data contains very few ATAC-seq data in each cancer type, so your tools provide us a great solution to explore the DHS status.  Howerver, TCGA harmonized data( RNAseq hg38 raw count and FPKM level 3 data ) is available and often used, this limited the usage of your tools. Although TCGA legacy data (RNAseq hg19 RSEM expected-count data) is available, it is now deprecated and never updated later.  It is much more convenient if you can provide pre-built hg38 model. Realigning DNase-seq and RNA-seq data to hg38 coordinates is an intensive work, hopefully you can upgrade this great tools in the up-coming version.

**Comment by WeiqiangZhou** [comment]
If you need a pre-built model for hg38 FPKM, I have built one and it has been released here: https://github.com/WeiqiangZhou/BIRD-model/releases/download/v1.4/human_hg38_model.bin.zip. Thanks for your suggestions.

**Comment by WeiqiangZhou** [comment]
Adding on to the previous comment, you can actually use TPM as input even if the model is built with FPKM since BIRD will do a quantile normalization to the input data. Because the only difference between FPKM and TPM is the scaling factor and it will become irrelevant after quantile normalization.
