### ISSUE TITLE
build prediction model using matched Bulk ATAC-seq and  RNAseq data

### ISSUE THREAD

**Issue by liangdp1984** [WeiqiangZhou/BIRD#8]
To build the prediction model, you suggest thar we should have normalized and log2 transformed DNase-seq data and the log2 transformed and quantile normalized gene expression data.  I don't have DNase-seq data,  I have matched Bulk ATAC-seq and  RNAseq data for 20 cancer patients, can I build prediction model using matched Bulk ATAC-seq and RNAseq data? if I can, is it the same way as DNase-seq data?

**Comment by WeiqiangZhou** [comment]
Yes, you can use the matched ATAC-seq and RNA-seq data to build a prediction model. ATAC-seq data are very similar to DNase-seq data. For data normalization, you can process the ATAC-seq data in the same way as the DNase-seq data.
