### ISSUE TITLE
GRCh38 based model

### ISSUE THREAD

**Issue by gianfilippo** [WeiqiangZhou/BIRD#9]
Hi,

have you trained a model based on the GRCh38 genome release ?

Also, if I were to use one of the existing models with a new RNAseq track, would you not expect that batch effect could influence the prediction?

Thanks
Gianfilippo

**Comment by WeiqiangZhou** [comment]
Yes, there is a pre-trained model available for GRCh38 (i.e., hg38).
https://github.com/WeiqiangZhou/BIRD-model

BIRD will do quantile normalization to the new input RNA-seq data which is the step we used to remove the potential batch effects.

**Comment by gianfilippo** [comment]
Hi,
sorry about the delay.
Thank you for the model!!
Best
Gianfilippo
